# Generated by Django 5.2.8 on 2025-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("VANGUARD", "Vanguard"),
                            ("DUELIST", "Duelist"),
                            ("STRATEGIST", "Strategist"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="heroes/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube video URL"),
                ),
                (
                    "tips",
                    models.TextField(blank=True, help_text="Your tips for this hero"),
                ),
                (
                    "playstyle_tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags like: mobility, burst-damage, area-control, dive, poke",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")],
                        default=2,
                        help_text="Difficulty to play (1-3)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Heroes this hero counters",
                        related_name="countered_by",
                        to="heroes.hero",
                    ),
                ),
                (
                    "synergies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Heroes this hero has synergy with",
                        related_name="synergy_with",
                        to="heroes.hero",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
