# Generated by Django 5.2.8 on 2025-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Banner image for team showcase",
                null=True,
                upload_to="heroes/banners/",
            ),
        ),
    ]
